### ISSUE TITLE
Has this been abandoned?

### ISSUE THREAD

**Issue by AlexCatch** [mawie81/electron-oauth2#33]
There seems to be very little activity & PRs that fix some breaking issues are not being merged.

**Comment by mawie81** [comment]
You are right and I'm very sorry for keeping this thing unmanaged for such a long time.
As my priorities have shifted and I'm not working with Electron anymore, I'm looking for people who would want to take this over.
So whoever wants to get involved, just let me know.

**Comment by aguynamedben** [comment]
@AlexCatch FWIW I'm using it for something important. The code is pretty small and simple to understand. I just submitted a PR for something I needed.

@mawie81 I don't have a lot of history being a great FOSS maintainer but I can help keep an eye on it or help merge PRs. I'm using it in an app that does 2 different service authentications (and more soon). I see the tests are disabled but I can at least smoke check PRs with my app in the near term.

If you're totally over it you can make me a maintainer and I'll try to be a good steward.

**Comment by aguynamedben** [comment]
@AlexCatch I'm going to help maintain this project. I'm actively using it in production for several APIs, so I at least have a good private codebase to smoke-check PRs with.

Recently merged PRs:
* https://github.com/mawie81/electron-oauth2/pull/34
* https://github.com/mawie81/electron-oauth2/pull/37

Let me know if you have any outstanding PRs/issues you'd like me to take a look at. Otherwise I'm going to go most recent to least recent in the next week or so.

Closing this because it's not abandoned!

**Comment by AlexCatch** [comment]
@aguynamedben Great! Thanks for taking this on, you rock.
